### ISSUE TITLE
indigo: need to release some ROS package dependencies

### ISSUE THREAD

**Issue by jack-oquin** [utexas-bwi/bwi#13]
To get our Hydro source tree working on Indigo, we need Indigo releases of:

- [x] eband_local_planner
- [x] libsegwayrmp
- [x] segway_rmp

As a work-around, those repositories can be added to everyone's source workspace.

**Comment by piyushk** [comment]
All downstream repositories released. Closing issue here.

**Comment by jack-oquin** [comment]
Once all these packages are in the ROS package repositories, we should delete them from ``bwi/rosinstall/indigo.rosinstall``
