### ISSUE TITLE
LDAP: login shell is /bin/sh, should be /bin/bash

### ISSUE THREAD

**Issue by jack-oquin** [utexas-bwi/bwi#23]
I did some config updates that were supposed to fix this, but bash (and zsh) are not in the list of possible shells for LDAP configuration when creating a new user.

I can login to hypnotoad, but my login shell is ``/bin/sh``. Not good.

cc: @piyushk

**Comment by jack-oquin** [comment]
I was able to update the shell via phpLDAPadmin, by adding a ``loginShell`` field set to ``/bin/bash``.

It did not work when initially creating the user ID.

**Comment by jack-oquin** [comment]
I fixed the three actual users already defined: joq, piyushk and bwi.

I'll leave this open until we can create a new user with the proper shell.

**Comment by jack-oquin** [comment]
The currently-recommended method of creating a new user is to copy from and existing one. Among other advantages, that approach bypasses this problem.

**Comment by arctiqjacob** [comment]
This can be fixed by editing: /usr/share/phpldapadmin/templates/creation/posixAccount.xml and at line 75, changing `<value id="/bin/sh">Bash</value>` to `<value id="/bin/bash">Bash</value>`
