### ISSUE TITLE
clamps: arduino firmware does not load

### ISSUE THREAD

**Issue by jack-oquin** [utexas-bwi/bwi#29]
Arduino IDE hangs with messages like:

```
avrdude: programmer is not responding
```

@piyushk: we had at least one Arduino in the lab with a broken firmware loader. It should have been labelled, but I am not certain what happened to it.

**Comment by piyushk** [comment]
@jack-oquin Thanks for letting me know. I'll look into it this weekend.

**Comment by piyushk** [comment]
@jack-oquin upload worked for me today. I was able to see sonar returns in rviz with `bwi_launch segbot_v2.launch`

**Comment by jack-oquin** [comment]
Good

**Comment by piyushk** [comment]
Unfortunately i might have burned the arduino on bender yesterday :(. I
will investigate today.

Piyush
