### ISSUE TITLE
rosinstall: update lists of source repositories

### ISSUE THREAD

**Issue by jack-oquin** [utexas-bwi/bwi#32]
Once multi_level_map is up-to-date in the ROS package repositories, it should be deleted from indigo.rosinstall.

@piyushk : What should we do about hydro.rosinstall? It probably won't work anymore.

* Delete it?
* Update it to use the hydro_devel branches? They will be rather down-level, compared to the sources on roberto.
* Make another, more recent branch that will likely work? Is that worth the effort and testing?

**Comment by jack-oquin** [comment]
At this point, I am inclined to just delete hydro.rosinstall and update the README accordingly.

**Comment by piyushk** [comment]
Sounds good to me.

Piyush

**Comment by jack-oquin** [comment]
OK. I'll wait to make the update until I get back to town. By then the multi_level_map debs should be up-to-date and I can delete that repo from indigo.rosinstall.
