### ISSUE TITLE
Add integration testing

### ISSUE THREAD

**Issue by pato** [utexas-bwi/bwi#38]
Want to look into the possibility of adding some sort of continuous integration testing. Travis CI is free for educational use, so it might be worth integrating.

At the very least ensure that any merge does not break the compilation of the codebase, eventually we might even want to add some integration/unit tests.

**Comment by jack-oquin** [comment]
+1

**Comment by jack-oquin** [comment]
The commit above is a first attempt to add Travis CI to bwi_common.

**Comment by jack-oquin** [comment]
The initial test (#54) failed, probably because not all packages define a ``roslint`` target.

**Comment by jack-oquin** [comment]
Apparently, the specific roslint targets don't work, either.
