### ISSUE TITLE
compilation issue in segway_rmp package

### ISSUE THREAD

**Issue by jsinapov** [utexas-bwi/bwi#41]
Upon setting up a workspace, the first catkin_make run produces the following error:

/home/users/jsinapov/catkin_ws/src/segway_rmp/src/segway_rmp_node.cpp:32:44: fatal error: segway_rmp/SegwayStatusStamped.h: No such file or directory
 #include "segway_rmp/SegwayStatusStamped.h"
                                            ^
compilation terminated.

Chances are, the CMakeLists.txt needs to specify that the message needs to be compiled before the segway_rmp_node is compiled.

**Comment by jack-oquin** [comment]
Does running it once or twice again resolve the error? If so, that's almost certainly the problem.

But, it looks like this issue is probably in the [segway_rmp](https://github.com/segwayrmp/segway_rmp) repository.

**Comment by jack-oquin** [comment]
I believe this is fixed now.
