### ISSUE TITLE
rosinstall file update for kinetic 

### ISSUE THREAD

**Issue by shihyunlo** [utexas-bwi/bwi#50]
I experienced the same issue as suggested in commit c37af4c:
https://github.com/utexas-bwi/segway_rmp/commit/c37af4c20fa71af144df65a5bf306de048b5ca9b

We probably should pull the the segway_rmp package from:
https://github.com/utexas-bwi/segway_rmp

**Comment by jack-oquin** [comment]
OK with me.

**Comment by jack-oquin** [comment]
Note that @rdelfin submitted a pull request (segwayrmp/segway_rmp#33) to update the main repository.

**Comment by jack-oquin** [comment]
The update was merged into the ``segwayrmp`` repo today, so no rosinstall change is needed.
