### ISSUE TITLE
Bring segbot_arm packages into the main repositories

### ISSUE THREAD

**Issue by nickswalker** [utexas-bwi/bwi#52]
Bringing these packages in has a few benefits:

* Simplifies the usage of the arm robot. No special workspace-creation procedures
* Sharing previously duplicated code will make future migrations, bug fixes easier
* Better integration will make moving the arm to an updated RMP base easier in the future

The cons include more packages in a default BWI workspace, but as @jack-oquin has highlighted, this is something that can be handled with `catkin_tools` blacklists. This will also have the effect of moving many previously centralized bits of arm infrastructure to their own separate corners.

After some discussion, @jack-oquin and I agreed that we're in a good position to do this now, as we're already going to induce a lot of changes with the Kinetic migration. I am especially interested in doing this quickly as @harely22 and @thomason-jesse are setting up to do more work on the platform.

I have already merged the launch/description/bringup components into the appropriate packages on the Kinetic branch, and I'll be moving the remaining packages soon.

**Comment by jack-oquin** [comment]
As Nick said, this seems like a good idea to me.

**Comment by jack-oquin** [comment]
I'd like to get our Kinetic branches in good shape to share **bwi_common** with the RoboCup@Home team.

**Comment by shihyunlo** [comment]
Would segbot_arm launch file remain separate from segbot_v3/v4? If so, it
sounds great to me; if not, we might need to test out the performance of
regular tasks (such as visit_door_list), to make sure both navigation and
kr_execution are not much slowed down.


2018-01-25 21:21 GMT-06:00 jack-oquin <notifications@github.com>:

**Comment by nickswalker** [comment]
The launch files will be in the same package now (bwi_launch), but they will remain separate. There should be no change at run time for any non-armed robot.

**Comment by shihyunlo** [comment]
Sounds great, I am happy with it.

2018-01-25 21:32 GMT-06:00 Nick Walker <notifications@github.com>:

**Comment by nickswalker** [comment]
This is done.

segbot_arm_perception was easy to promote into bwi_common (nice win for RoboCup), but segbot_arm_tasks is stuck separate from bwi_tasks because of segbot_arm_manipulation. We need a better abstraction over basic manipulation capabilities.

**Comment by jack-oquin** [comment]
Our current launch scripts have evolved into a bit of a hairball over the years. Fixing that is clearly outside the scope of this issue.

I have some ideas how to make them much more modular, and may open a separate issue for that.

**Comment by jack-oquin** [comment]
Note that due to new packages and dependencies, people will probably want to check out new workspaces from scratch.

**Comment by jack-oquin** [comment]
I am getting an unresolved dependency:
```
$ rosdep install --from-paths src --ignore-src --rosdistro=kinetic
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
kinova_arm_moveit_demo: Cannot locate rosdep definition for [pr2_moveit_plugins]
```

**Comment by jack-oquin** [comment]
That problem is in our copy of the **kinova-ros** repo. Putting CATKIN_IGNORE in the **kinova_arm_moveit_demo** package there works around it temporarily.

**Comment by nickswalker** [comment]
It seems that there isn't a kinetic release of that package yet. I don't know that we have every referenced that demo, so although I am somewhat uncomfortable with the practice, I think it may be fine to commit the ignore file and let the kinova folks fix it whenever they get around to it.

**Comment by jack-oquin** [comment]
I cherry-picked 59e78f16bd06e7197b9419e2d31fd92d963d5163 into master, because the generic BWI install instructions use that branch.

**Comment by jack-oquin** [comment]
I agree about the CATKIN_IGNORE hack, but went ahead to avoid messing up other people's work flow.

**Comment by jack-oquin** [comment]
WIth the CATKIN_IGNORE I can download, build and run some basic BWI navigation tests.

**Comment by jack-oquin** [comment]
xref: utexas-bwi/kinova-ros#3
